let suggestions = [
    // About Web
    "Channel",
    "CodingLab",
    "CodingNepal",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Blogger",
    "Bollywood",
    "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to become Freelancer",
    "How to become Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    // Singers
    "周杰伦",
    "林俊杰",
    "薛之谦",
    // Songs
    "What does CSS stands for?",
    "What does CSS stands for?",
    "What does CSS stands for?",
    "What does CSS stands for?",
    "What does CSS stands for?",
    "What does CSS stands for?",
    "What does CSS stands for?",
    "What does CSS stands for?",
];
